"""Daily TW stock push: summary table first, then per-stock detail embeds.

Reads picks.json, builds 1 summary + N pick + 1 disclaimer embeds, sends in order.

Usage:
    python daily_push.py [picks.json]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from send_discord import send_embeds

ROOT = Path(__file__).resolve().parent

COLOR_HEADER = 0x0984E3
COLOR_BUY = 0x00B894
COLOR_HOLD = 0xFDCB6E
COLOR_RISK = 0xD63031
COLOR_DISCLAIMER = 0x636E72


def fmt_pct(x: float) -> str:
    return f"{x:+.1f}%"


def fmt_num(x: float, decimals: int = 2) -> str:
    return f"{x:,.{decimals}f}"


def rating_for(upside: float) -> tuple[str, str, int]:
    """Return (emoji_rating, action_hint, color)."""
    if upside >= 20:
        return ("🟢 首選/核心", "現價可分批進場", COLOR_BUY)
    if upside >= 10:
        return ("🟢 進場", "現價可分批進場", COLOR_BUY)
    if upside >= 0:
        return ("🟡 偏高", "建議分批承接、等回檔加碼", COLOR_HOLD)
    if upside >= -10:
        return ("🔴 等回", "估值偏滿、等明顯回檔", COLOR_RISK)
    return ("🔴 追高風險", "本益比過高、不建議追高", COLOR_RISK)


def build_summary_embed(meta: dict, picks: list[dict]) -> dict:
    lines = ["```"]
    lines.append(f"{'#':<2} {'標的':<12} {'現價':>6}  {'目標':>6}  {'空間':>7}  評等")
    lines.append("-" * 54)
    for i, p in enumerate(picks, start=1):
        up = p["upside_base_pct"]
        rating, _, _ = rating_for(up)
        name_code = f"{p['name']} {p['ticker']}"
        lines.append(
            f"{i:<2} {name_code:<12} "
            f"{p['price']:>6,.0f}  {p['targets']['base']:>6,.0f}  "
            f"{up:>+6.1f}%  {rating}"
        )
    lines.append("```")
    table = "\n".join(lines)

    desc = (
        f"📅 **報告日期**：{meta['date']}\n"
        f"📈 **大盤狀態**：{meta['taiex']}　YTD {meta['ytd']}\n"
        f"🎯 **主軸**：{meta['theme']}\n\n"
        f"## 推薦排序（按 Base 上漲空間）\n{table}\n"
        "**評等說明**\n"
        "🟢 = base case 仍有 ≥10% 空間，可現價分批進場\n"
        "🟡 = 已大幅 re-rate，建議分批承接\n"
        "🔴 = 估值偏高，建議等回檔（個股建議價位見下）\n\n"
        "👇 各檔詳細財報、三情境 EPS、目標價、催化劑與風險見以下分則"
    )
    upcoming = meta.get("upcoming_catalysts")
    if upcoming:
        desc += f"\n\n📌 **近期關注事件**\n{upcoming}"

    return {
        "title": f"📊 台股潛力標的 每日更新（{meta['date']}）",
        "description": desc[:4096],
        "color": COLOR_HEADER,
        "footer": {"text": f"Generated by Claude Code · {meta['generated_at']}"},
    }


def build_pick_embed(idx: int, p: dict) -> dict:
    up = p["upside_base_pct"]
    rating, action, color = rating_for(up)
    targets = p["targets"]
    scenarios = p["scenarios"]

    fields = [
        {
            "name": "💰 目前狀態",
            "value": (
                f"**現價** NT${fmt_num(p['price'])}\n"
                f"**市值** NT${p['market_cap_str']}\n"
                f"**Trailing P/E** {fmt_num(p['pe_trailing'], 1)}x\n"
                f"**2026 Fwd P/E** {fmt_num(p['pe_forward'], 1)}x"
            ),
            "inline": True,
        },
        {
            "name": "🎯 目標價（12個月）",
            "value": (
                f"**Bear** NT${fmt_num(targets['bear'])}\n"
                f"**Base** NT${fmt_num(targets['base'])}　**({fmt_pct(up)})**\n"
                f"**Bull** NT${fmt_num(targets['bull'])}\n"
                f"**評等** {rating}"
            ),
            "inline": True,
        },
        {
            "name": "📈 2026 EPS 三情境 (NT$)",
            "value": (
                f"Bear {fmt_num(scenarios['bear'])} ｜ "
                f"Base **{fmt_num(scenarios['base'])}** ｜ "
                f"Bull {fmt_num(scenarios['bull'])}"
            ),
            "inline": False,
        },
        {
            "name": "🔥 近期財報亮點",
            "value": p["financial_highlight"][:1024],
            "inline": False,
        },
        {
            "name": "⚡ 催化劑",
            "value": "\n".join(f"• {c}" for c in p["catalysts"])[:1024],
            "inline": False,
        },
        {
            "name": "⚠️ 主要風險",
            "value": "\n".join(f"• {r}" for r in p["risks"])[:1024],
            "inline": False,
        },
        {
            "name": f"💡 推薦理由（{action}）",
            "value": p["reason"][:1024],
            "inline": False,
        },
    ]
    return {
        "title": f"#{idx}  {p['name']} ({p['ticker']})  {rating}",
        "color": color,
        "fields": fields,
        "footer": {"text": f"資料來源：{p.get('sources_short', 'WebSearch / 法說會 / 法人報告')}"},
    }


def build_disclaimer_embed() -> dict:
    return {
        "title": "📋 重要聲明",
        "description": (
            "1. 本內容由 AI 自動整理，**非投資建議**，不構成買賣邀約。\n"
            "2. 目標價基於 P/E × EPS 簡化估值，未涵蓋總體經濟、地緣政治、匯率等系統性風險。\n"
            "3. 12 個月目標價為估計值，實際走勢可能大幅偏離。\n"
            "4. 投資前請參閱公開資訊觀測站最新公告，並諮詢合格理財顧問。\n"
            "5. 過去績效不保證未來表現。"
        ),
        "color": COLOR_DISCLAIMER,
    }


def push(picks_file: Path) -> None:
    data = json.loads(picks_file.read_text(encoding="utf-8"))
    meta = data["meta"]
    picks = data["picks"]

    embeds: list[dict] = [build_summary_embed(meta, picks)]
    for i, p in enumerate(picks, start=1):
        embeds.append(build_pick_embed(i, p))
    embeds.append(build_disclaimer_embed())

    send_embeds(embeds=embeds, content="📬 **台股潛力標的 每日更新**")
    print(f"sent {len(embeds)} embeds ({len(picks)} picks)")


if __name__ == "__main__":
    picks_path = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "picks.json"
    push(picks_path)
