"""Format and push TW stock picks to Discord as rich embeds.

Reads a JSON file of picks and pushes each as one embed, plus an intro embed.
Usage:
    python push_picks.py picks.json
"""
from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

from send_discord import send_embeds

ROOT = Path(__file__).resolve().parent

COLOR_HEADER = 0x2D3436
COLOR_BUY = 0x00B894
COLOR_HOLD = 0xFDCB6E
COLOR_RISK = 0xD63031


def fmt_pct(x: float) -> str:
    return f"{x:+.1f}%"


def fmt_num(x: float, decimals: int = 2) -> str:
    return f"{x:,.{decimals}f}"


def build_intro_embed(meta: dict) -> dict:
    return {
        "title": f"📊 台股潛力標的推薦  ({meta['date']})",
        "description": (
            f"**大盤狀態**：加權指數 {meta['taiex']}，YTD {meta['ytd']}\n"
            f"**主軸**：{meta['theme']}\n"
            f"**選股條件**：市值 ≥ 100 億、6–12 個月視野、均衡配置\n"
            f"**標的數**：{meta['n_picks']} 檔（依推薦強度排序）\n\n"
            f"⚠️ 本內容為 AI 整理之研究筆記，**非投資建議**。"
            f"請務必自行查證最新財報與股價，投資前評估自身風險承受度。"
        ),
        "color": COLOR_HEADER,
        "footer": {"text": f"Generated by Claude Code · {meta['generated_at']}"},
    }


def build_pick_embed(idx: int, p: dict) -> dict:
    color = COLOR_BUY if p["upside_base_pct"] >= 20 else COLOR_HOLD
    title = f"#{idx}  {p['name']} ({p['ticker']})"

    scenarios = p["scenarios"]
    targets = p["targets"]
    fields = [
        {
            "name": "💰 目前狀態",
            "value": (
                f"**現價** NT${fmt_num(p['price'])}\n"
                f"**市值** NT${p['market_cap_str']}\n"
                f"**Trailing P/E** {fmt_num(p['pe_trailing'], 1)}x\n"
                f"**2026 Fwd P/E** {fmt_num(p['pe_forward'], 1)}x"
            ),
            "inline": True,
        },
        {
            "name": "🎯 目標價（12個月）",
            "value": (
                f"**Bear** NT${fmt_num(targets['bear'])}\n"
                f"**Base** NT${fmt_num(targets['base'])}\n"
                f"**Bull** NT${fmt_num(targets['bull'])}\n"
                f"**Base 上漲空間** {fmt_pct(p['upside_base_pct'])}"
            ),
            "inline": True,
        },
        {
            "name": "📈 2026 EPS 三情境 (NT$)",
            "value": (
                f"Bear {fmt_num(scenarios['bear'])} ｜ "
                f"Base **{fmt_num(scenarios['base'])}** ｜ "
                f"Bull {fmt_num(scenarios['bull'])}"
            ),
            "inline": False,
        },
        {
            "name": "🔥 近期財報亮點",
            "value": p["financial_highlight"][:1024],
            "inline": False,
        },
        {
            "name": "⚡ 催化劑",
            "value": "\n".join(f"• {c}" for c in p["catalysts"])[:1024],
            "inline": False,
        },
        {
            "name": "⚠️ 主要風險",
            "value": "\n".join(f"• {r}" for r in p["risks"])[:1024],
            "inline": False,
        },
        {
            "name": "💡 推薦理由",
            "value": p["reason"][:1024],
            "inline": False,
        },
    ]
    return {
        "title": title,
        "color": color,
        "fields": fields,
        "footer": {"text": f"資料來源：{p.get('sources_short', 'WebSearch / 法說會 / 法人報告')}"},
    }


def build_disclaimer_embed() -> dict:
    return {
        "title": "📋 重要聲明",
        "description": (
            "1. 本推薦由 AI 自動整理，**非投資建議**，不構成買賣邀約。\n"
            "2. 目標價基於 P/E × EPS 的簡化估值，未涵蓋總體經濟、地緣政治、匯率等風險。\n"
            "3. 12 個月目標價只是估計，實際走勢可能大幅偏離。\n"
            "4. 投資前請參閱公開資訊觀測站最新公告，並諮詢合格理財顧問。\n"
            "5. 過去績效不保證未來表現。"
        ),
        "color": COLOR_RISK,
    }


def push(picks_file: Path) -> None:
    data = json.loads(picks_file.read_text(encoding="utf-8"))
    meta = data["meta"]
    picks = data["picks"]

    embeds: list[dict] = [build_intro_embed(meta)]
    for i, p in enumerate(picks, start=1):
        embeds.append(build_pick_embed(i, p))
    embeds.append(build_disclaimer_embed())

    send_embeds(embeds=embeds, content="📬 **台股潛力標的分析推播**")
    print(f"sent {len(embeds)} embeds ({len(picks)} picks)")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: python push_picks.py <picks.json>")
        sys.exit(1)
    push(Path(sys.argv[1]))
